### ISSUE TITLE
HarborCluster updateStrategyType is not propagated into individual component deployments

### ISSUE THREAD

**Issue by karaguo** [goharbor/harbor-operator#1015]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**

All harbor deployments such as registry, core, and etc. don’t follow the strategy set by harborcluster. When HarborCluster [updateStrategyType](https://github.com/goharbor/harbor-operator/blob/9c19b151ff71f66f9079236e4dc4ce3d4a1e02c3/apis/goharbor.io/v1beta1/harborcluster_types.go#L87) is set, the value is only set to CRD Harbor [link](https://github.com/goharbor/harbor-operator/blob/9c19b151ff71f66f9079236e4dc4ce3d4a1e02c3/pkg/cluster/controllers/harbor/harbor.go#L125), but not propagated into the deployment strategy https://pkg.go.dev/k8s.io/api/apps/v1#DeploymentStrategy of components such as registry. 

**Steps to reproduce the problem:**

1. Set harborcluster updateStrategyType value to `Recreate`
2. All deployments strategy is still default value `RollingUpdate`

**Versions:**
Please specify the versions of following systems.

- harbor operator version: 1.2.0
- harbor version: 2.6.2
- kubernetes version: 1.24.2

**Comment by BRONSOLO** [comment]
Any updates on this ticket? ty!

**Comment by karaguo** [comment]
> Any updates on this ticket? ty!

Fixed by https://github.com/goharbor/harbor-operator/pull/1016
