### ISSUE TITLE
The controller runtime version is too early

### ISSUE THREAD

**Issue by CoderTH** [goharbor/harbor-operator#1033]
What can we help you?

We rely on harbor-operator in our project. harbor-operator is the ```sigs.k8s.io/controller-runtime v0.12.3``` package. But this package has a break change in v0.14.0 to remove ```pkg/envtest/printer```
![image](https://github.com/goharbor/harbor-operator/assets/51119718/8e8ffcf1-32d1-4546-b32d-f48565d98e0b)

and we also rely on other projects that use controller runtime above ```v0.14.0``` and use its new features. So there was some conflict, and I wanted to ask if our community was planning to update the version of controller-runtime, or could I help with that?

**Comment by MarcelMue** [comment]
This should be done in master now.
