### ISSUE TITLE
rename "master" branch to "main"

### ISSUE THREAD

**Issue by OrlinVasilev** [goharbor/harbor-operator#1049]
As CNCF project we should work towards more inclusive language and renaming the "master" branch to "main" is a good starting point!

**Comment by keerthi-nallaginela** [comment]
Hi, Can I take this up?

**Comment by OrlinVasilev** [comment]
@keerthi-nallaginela it's admin level action this issue it's for tracking purposes only!
@MarcelMue fyi

**Comment by thcdrt** [comment]
@wy65701436 renamed master to main.
We still need to update documentations.

**Comment by OrlinVasilev** [comment]
great :)) will post into the channel/mail and twitter folks to update :)
