### ISSUE TITLE
It seems Harbor CR does not update

### ISSUE THREAD

**Issue by steven-zou** [goharbor/harbor-operator#118]
Reproduce steps:

install harbor core components with `make sample`, harbor "sample" is deployed 

install full harbor with `make sample-harbor-full`, no more components are deployed.

expectations: the optional components like `notary`, `chartmuseum` and `trivy` should be deployed.

**Comment by bitsf** [comment]
there's still an error when install harbor-full
![image](https://user-images.githubusercontent.com/188115/97554589-f3ae8880-1a11-11eb-9bfd-cbe32bcac079.png)

**Comment by bitsf** [comment]
notary and trivy components are using github token which is not correctly injected.
