### ISSUE TITLE
password is not correct after `make sample` install

### ISSUE THREAD

**Issue by bitsf** [goharbor/harbor-operator#120]
commit:c33624540ccf5ff984193a43e8d963ff45a87b3e

The password set in `https://github.com/goharbor/harbor-operator/blob/c33624540ccf5ff984193a43e8d963ff45a87b3e/config/samples/harbor/kustomization.yaml#L24`
But after install by `make sample`, can not login
![image](https://user-images.githubusercontent.com/188115/94027950-fd7b1580-fded-11ea-947d-7d4ffbd0eef3.png)

**Comment by holyhope** [comment]
Can you check that:

- The postgresql persistent volume is new (fresh install)
- The password did not change between the installation and the time you tried to login

I will try to reproduce it on my side

**Comment by bitsf** [comment]
all fresh install
the password should be Harbor12345 by default, but not a messy code

**Comment by steven-zou** [comment]
duplicated with #138
