### ISSUE TITLE
the password can not be updated

### ISSUE THREAD

**Issue by bitsf** [goharbor/harbor-operator#122]
1. install harbor-operator
2. `make sample` to install harbor
3. change password of admin-core-secret in config/samples/harbor/kustomization.yaml
4. `make sample` to update harbor
5. the harbor password is not changed

I can see the secret is created, but seems the adminInitialPasswordRef is not updated to use this new one

**Comment by steven-zou** [comment]
@bitsf 

Can you make sure if this issue has been fixed. If yes, then close it.
