### ISSUE TITLE
can't helm install operator if not install extra cert-manager

### ISSUE THREAD

**Issue by bitsf** [goharbor/harbor-operator#149]
- not install any cert-manager
- make sure `certmanager.enabled=true` in `charts/harbor-operator/values.yaml`
- make helm-install
![image](https://user-images.githubusercontent.com/188115/97309779-6ea26280-189d-11eb-82b0-dfa77722819f.png)

install failed

**Comment by bitsf** [comment]
user has to install cert-manager crd first
$ kubectl apply --validate=false -f https://github.com/jetstack/cert-manager/releases/download/v0.16.0/cert-manager.crds.yaml

**Comment by bitsf** [comment]
can't find a method to pass installCRDs=true to the cert-manager dependency.
it seems `import-values` not working.

**Comment by bitsf** [comment]
there seems another problem, the webhook in crds.yaml is using a fixed namespace `cert-manager`, which will lead our integrated cert-manager working abnormal
![image](https://user-images.githubusercontent.com/188115/97957231-95a0ed00-1de5-11eb-9df1-7aae26cce13a.png)

**Comment by steven-zou** [comment]
we have moved the cert-manager installation from the harbor chart and then cert-manager should be installed before installing harbor.

close this issue now.
