### ISSUE TITLE
Support Redis sentinel mode

### ISSUE THREAD

**Issue by steven-zou** [goharbor/harbor-operator#158]
What can we help you?

**Comment by shadiramadan** [comment]
For what it's worth my org was having a lot of trouble with redis sentinel that we dropped the [spotahome/redis-operator](https://github.com/spotahome/redis-operator) for [amaizfinance/redis-operator](https://github.com/amaizfinance/redis-operator)

> Redis Operator can be considered a Kubernetes-native replacement for Redis Sentinel

Sentinels are a pain to work with, sentinel support isn't always available- and it is wonky to use especially when you just want to port forward to inspect and use the redis-cli

Kubernetes should manage routing for HA not sentinels.  The project is young and sure it isn't heavily used but it looks solid so far.
