### ISSUE TITLE
during install harbor, there's many error log

### ISSUE THREAD

**Issue by bitsf** [goharbor/harbor-operator#176]
cannot set status to error: cannot set conditions to error: cannot prepare owner status: cannot update status: Operation cannot be fulfilled on harbors.goharbor.io \"sample\": the object has been modified; please apply your changes to the latest version and try again: cannot prepare owner status: cannot update status: Operation cannot be fulfilled on harbors.goharbor.io \"sample\": the object has been modified; please apply your changes to the latest version and try again
![image](https://user-images.githubusercontent.com/188115/98113914-522aa980-1edf-11eb-8ac9-a7be8d52535d.png)

**Comment by steven-zou** [comment]
This is because the object has been outdated when doing status updates. No high influence so far, we can do some improvements later when we get a stable version.

**Comment by steven-zou** [comment]
Close as it is not valid anymore.
