### ISSUE TITLE
"kubernetes-charts.storage.googleapis.com" is deprecated for "stable" and will be deleted Nov. 13, 2020.

### ISSUE THREAD

**Issue by bitsf** [goharbor/harbor-operator#182]
There's a warning when install harbor-operator helm
kubernetes-charts.storage.googleapis.com" is deprecated for "stable" and will be deleted Nov. 13, 2020.

**Comment by steven-zou** [comment]
switch to artifact hub?

**Comment by steven-zou** [comment]
@bitsf 

we can do the migration to avoid the message.

**Comment by bitsf** [comment]
not exists in recent build now
