### ISSUE TITLE
CRDs are not deleted when `helm delete harbor-operator`

### ISSUE THREAD

**Issue by bitsf** [goharbor/harbor-operator#183]
steps:
1. make helm-install
2. helm delete harbor-operator
3. kubectl get crd|grep harbor
![image](https://user-images.githubusercontent.com/188115/98217722-d7689980-1f85-11eb-98c3-0c71ea70ff11.png)

all resources create by helm should be also deleted when helm delete

**Comment by kfox1111** [comment]
I would call this a feature. If you have multiple harbors you don't want all the harbors to go away when you delete just one. I usually try and prevent helm from managing crd's at all to avoid this.
