### ISSUE TITLE
Same `ConfigImageKey` for components when get image. It must different for components.

### ISSUE THREAD

**Issue by wangcanfengxs** [goharbor/harbor-operator#187]
I want to set custom image for every compoents through

```
func (r *Reconciler) GetImage(ctx context.Context) (string, error) {
	image, err := r.ConfigStore.GetItemValue(ConfigImageKey)
	if err != nil {
		if _, ok := err.(configstore.ErrItemNotFound); !ok {
			return "", err
		}

		image = DefaultImage
	}

	return image, nil
}
```

But every components use same key (`ConfigImageKey="docker-image"`) to get the image. I can not set different for different components.

I think the ConfigStore is global, isn't it?

**Comment by steven-zou** [comment]
Is `ConfigStore` for each `Reconciler` initialized with some key prefix? We need to clarify this question.

**Comment by steven-zou** [comment]
@holyhope 

Any answer here?

**Comment by steven-zou** [comment]
Confirmed, `setup.Controller` will initialize configStore for each of the CR controllers and set env prefix using the name of the CR controllers.

```go
func (c *controller) GetConfig(ctx context.Context) (*configstore.Store, error) {
	configStore := config.NewConfigWithDefaults()
	configStore.Env(c.Name.String()) // <=====HERE!

	return configStore, nil
}
```
