### ISSUE TITLE
There should be a CR for configuration.

### ISSUE THREAD

**Issue by reasonerjt** [goharbor/harbor-operator#188]
Some configurations have to be set by Harbor API after it's started.

As for the operator, there should be a CR in operator such that user can set app level configuration such as 
`auth_mode`, `robot_prefix` etc.

**Comment by steven-zou** [comment]
I think configmap is enough to handle this case

**Comment by steven-zou** [comment]
write a ctrl to watch an annoated confgmap and then autoload and populate properties
