### ISSUE TITLE
Make field "imageChartStorage" in io.goharbor.v1alpha2.HarborCluster.spec optional

### ISSUE THREAD

**Issue by wangcanfengxs** [goharbor/harbor-operator#201]
ValidationError When I apply a HarborCluster cr. 

The HarborCluster "harborcluster-sample" is invalid:
* spec.database: Required value
* spec.imageChartStorage: Required value
* spec.redis: Required value

**Comment by steven-zou** [comment]
FIXED in PR: https://github.com/goharbor/harbor-operator/pull/235
