### ISSUE TITLE
Install Redis, Postgresql,  MinIO CRD at first

### ISSUE THREAD

**Issue by wangcanfengxs** [goharbor/harbor-operator#205]
Occur error when I make run, I think we need install Redis, Postgresql, minIO CRD at first

2020-11-24T10:30:38.566+0800	ERROR	harbor-operator.controller	error when reconcile cache component.	{"controller": "harborcluster", "error": "the server could not find the requested resource"}
github.com/go-logr/zapr.(*zapLogger).Error
	/root/harbor-operator/vendor/github.com/go-logr/zapr/zapr.go:132
github.com/goharbor/harbor-operator/controllers/goharbor/harborcluster.(*Reconciler).AddResources
	/root/harbor-operator/controllers/goharbor/harborcluster/resources.go:31
github.com/goharbor/harbor-operator/pkg/controller.(*Controller).Run
	/root/harbor-operator/pkg/controller/common.go:149
github.com/goharbor/harbor-operator/pkg/controller.(*Controller).Reconcile
	/root/harbor-operator/pkg/controller/common.go:119
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/root/harbor-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:235
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/root/harbor-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:209
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker
	/root/harbor-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:188
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1
	/root/harbor-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155
k8s.io/apimachinery/pkg/util/wait.BackoffUntil
	/root/harbor-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156
k8s.io/apimachinery/pkg/util/wait.JitterUntil
	/root/harbor-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133
k8s.io/apimachinery/pkg/util/wait.Until
	/root/harbor-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90

**Comment by steven-zou** [comment]
Provide kustomization manifests for deploying the whole stack, see https://github.com/goharbor/harbor-operator/issues/213
