### ISSUE TITLE
Use meaningful name prefix for Redis related resource

### ISSUE THREAD

**Issue by steven-zou** [goharbor/harbor-operator#219]
at least adding prefix `redisfailover-`/`redis`, not `rfs`/ `rfr`

**Comment by chlins** [comment]
I think we can align harbor other components like 'harbor-sample-core', add suffix '-redis' for related resources, ex: harbor-sample-redis.

**Comment by chlins** [comment]
I think we can align harbor other components like 'harbor-sample-core', add suffix '-redis' for related resources, ex: harbor-sample-redis.

**Comment by chlins** [comment]
Resolved by https://github.com/goharbor/harbor-operator/pull/233
