### ISSUE TITLE
MinIO can not be deployed.

### ISSUE THREAD

**Issue by chlins** [goharbor/harbor-operator#224]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
A clear and concise description of what you expected to happen and what's the actual behavior. If applicable, add screenshots to help explain your problem.

**Steps to reproduce the problem:**
Please provide the steps to reproduce this problem.

**Versions:**
Please specify the versions of following systems.

- harbor operator version: [x.y.z]
- harbor version: [x.y.z]
- kubernetes version: [x.y.z]
- Any additional relevant versions such as CertManager

**Additional context:**

- **Harbor dependent services:**
  - Context info of postgreSQL
  - Context info of Redis
  - Context info of storage
- **Log files:** Collect logs and attach them here if have.
- **Kubernetes:** How Kubernetes access was provided (what cloud provider, service-account configuration, ...).

![image](https://user-images.githubusercontent.com/31262637/100411377-922f1780-30ac-11eb-9326-e7f99205a62a.png)

**Comment by soulseen** [comment]
which MinIO operator version are you installed?

**Comment by chlins** [comment]
> which version of MinIO operator are you installed?

My MinIO operator was installed by `kubectl krew install minio` and `kubectl minio init`.

**Comment by chlins** [comment]
duplicates https://github.com/goharbor/harbor-operator/issues/240
