### ISSUE TITLE
Postgres health check ping operation was canceled.

### ISSUE THREAD

**Issue by chlins** [goharbor/harbor-operator#225]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
A clear and concise description of what you expected to happen and what's the actual behavior. If applicable, add screenshots to help explain your problem.

**Steps to reproduce the problem:**
Please provide the steps to reproduce this problem.

**Versions:**
Please specify the versions of following systems.

- harbor operator version: [x.y.z]
- harbor version: [x.y.z]
- kubernetes version: [x.y.z]
- Any additional relevant versions such as CertManager

**Additional context:**

- **Harbor dependent services:**
  - Context info of postgreSQL
  - Context info of Redis
  - Context info of storage
- **Log files:** Collect logs and attach them here if have.
- **Kubernetes:** How Kubernetes access was provided (what cloud provider, service-account configuration, ...).

![image](https://user-images.githubusercontent.com/31262637/100412219-fa7ef880-30ae-11eb-826c-81a45f8a50a7.png)

**Comment by Ghostbaby** [comment]
this issue looks like something wrong with the context.
