### ISSUE TITLE
Harbor status based on other resources status

### ISSUE THREAD

**Issue by holyhope** [goharbor/harbor-operator#28]
Harbor resource status should be based on dependencies status.
Suggestion: Ensure all deployments are `ready` to set Harbor to `ready`.

Reminder: for now, to check the Harbor readiness, the operator calls the `/api/health` (through the *apiserver*).
The new way should reduce resource consumption and will be finer status message.

**Comment by steven-zou** [comment]
work has been done, close this issue now.
