### ISSUE TITLE
harbor-core pod can't create successful

### ISSUE THREAD

**Issue by bitsf** [goharbor/harbor-operator#295]
`kubectl apply -f manifests/samples/full_stack.yaml` meet error in harbor-core pod
secret "harborcluster-sample-harbor-harbor-core-tokencert" not found
secret "sample-public-certificate" not found
![image](https://user-images.githubusercontent.com/188115/101433674-739b0d00-3945-11eb-9d04-4b574e5e6967.png)
![image](https://user-images.githubusercontent.com/188115/101433970-81509280-3945-11eb-93b9-5523fdaa7b23.png)
![image](https://user-images.githubusercontent.com/188115/101434380-93cacc00-3945-11eb-99da-19a97df5f0ec.png)

**Comment by bitsf** [comment]
there is secret `harborcluster-sample-harbor-harbor-core-tokencert-vwg6c` but not `harborcluster-sample-harbor-harbor-core-tokencert`

**Comment by aishwarya-aadi** [comment]
I am facing same issue. Can i please know how it was resolved? @bitsf
