### ISSUE TITLE
Enable CI/CD pipeline with github action

### ISSUE THREAD

**Issue by steven-zou** [goharbor/harbor-operator#3]
Cover:
  - CODE (lint, vet, race )
  - UT
  - Verify if it can work well in cluster (kind/minikube etc.）

**Comment by holyhope** [comment]
Still missing unit tests and deployment tests

**Comment by steven-zou** [comment]
Moreover, the GitHub action workflow should have one overall name, something like 'CI/CD'. Currently, I can see 4 action workflows.

You can check it in the `Action` tab.
