### ISSUE TITLE
harbor-registry and harbor-registryctl pod can not running

### ISSUE THREAD

**Issue by chlins** [goharbor/harbor-operator#305]
What can we help you?

![image](https://user-images.githubusercontent.com/31262637/101585739-5a649000-3a1b-11eb-9a20-2fd1c4aa8e5f.png)

![image](https://user-images.githubusercontent.com/31262637/101585795-78ca8b80-3a1b-11eb-9a74-45e001eb3040.png)

Maybe secret data field info is not correct.

**Comment by steven-zou** [comment]
@soulseen 

name mismatch?

**Comment by bitsf** [comment]
controllers/goharbor/registry/deployments.go:301
method ApplyS3StorageEnvs() is using key `harbormetav1.SharedSecretKey` which is named `secret`, not `s3`

**Comment by steven-zou** [comment]
`secret` is so general
