### ISSUE TITLE
harbor-core pod CrashLoopBackOff

### ISSUE THREAD

**Issue by chlins** [goharbor/harbor-operator#306]
What can we help you?

![image](https://user-images.githubusercontent.com/31262637/101585913-b9c2a000-3a1b-11eb-8f73-e08a2d7d50e4.png)
![image](https://user-images.githubusercontent.com/31262637/101585944-c8a95280-3a1b-11eb-819e-d0b0ad106964.png)

The Core pod can not connect to the database correctly, so fatal.

**Comment by steven-zou** [comment]
@Ghostbaby @wangcanfengxs 

We did not correctly set the password of the database when passing info to the Harbor CR.
