### ISSUE TITLE
Allow user to customize the certificate of external S3 endpoint

### ISSUE THREAD

**Issue by reasonerjt** [goharbor/harbor-operator#307]
When user is configuring external S3 endpoint as registry's storage, we need to make sure there're attributes in the manifest for configuring the cert or CA so that Harbor can use the storage service when it is serving HTTPs with self-signed certificate.

**Comment by steven-zou** [comment]
PRing: https://github.com/goharbor/harbor-operator/pull/373

**Comment by steven-zou** [comment]
I think we need to enhance the `imagechartsorage.S3` spec to support customized certs

**Comment by steven-zou** [comment]
Supported now
