### ISSUE TITLE
[blocker]:Support customization of Harbor's Image and pull secret.

### ISSUE THREAD

**Issue by reasonerjt** [goharbor/harbor-operator#331]
Due to the ratelimitation of dockerhub, we want to store Harbor's images to another registry  and use a pull secret.

The harbor operator should make such values configurable.  

This is becoming a blocker.

**Comment by steven-zou** [comment]
Now, we can customize the image paths of all the deployment.

For the image pulling secret, only harbor components support secret settings.

For the service components, pulling secrets will still not be supported. see https://github.com/goharbor/harbor-operator/pull/344
