### ISSUE TITLE
Support NCP(NSX) ingress controller

### ISSUE THREAD

**Issue by ywk253100** [goharbor/harbor-operator#337]
The path patterns are different for different ingress controllers, please refer to https://github.com/goharbor/harbor-helm/blob/master/templates/ingress/ingress.yaml#L12

**Comment by steven-zou** [comment]
For core ingress, it has been supported.

Now. only the minio ingress does not support ncp yet.

**Comment by steven-zou** [comment]
Checked, it seems only core need to handle the case. notary and minio does not need to handle different ingress controller as root path `/` is exposed.

**Comment by steven-zou** [comment]
Follow up refactor work will be tracked by https://github.com/goharbor/harbor-operator/issues/353.

**Comment by ywk253100** [comment]
Reopen this issue as there are still several issues when using NCP ingress

**Comment by ywk253100** [comment]
1. Several annotations are missing, please refer to https://github.com/goharbor/harbor-helm/blob/master/templates/ingress/ingress.yaml#L46
2. The path for portal should be `/.*` rather than `/` (https://github.com/goharbor/harbor-operator/blob/develop/controllers/goharbor/harbor/ingresses.go#L259)
3. The `notary` and `minio` should also support NCP(`/.*`)
4. Cannot work when the internal TLS enabled, don't know why, need more investigation

**Comment by steven-zou** [comment]
For this item 

> Cannot work when the internal TLS enabled, don't know why, need more investigation

If there are new founding, create new issues to track

**Comment by steven-zou** [comment]
> 1. Several annotations are missing, please refer to https://github.com/goharbor/harbor-helm/blob/master/templates/ingress/ingress.yaml#L46
> 2. The path for portal should be `/.*` rather than `/` (https://github.com/goharbor/harbor-operator/blob/develop/controllers/goharbor/harbor/ingresses.go#L259)
> 3. The `notary` and `minio` should also support NCP(`/.*`)

All the above items have been done. Close this issue.
