### ISSUE TITLE
The registry and registryctl can be put into one pod

### ISSUE THREAD

**Issue by ywk253100** [goharbor/harbor-operator#341]
The registry and registry controller can be put into one pod. Currently they are separated pods

**Comment by steven-zou** [comment]
considering one container one process model, maybe we should keep the current structure.

**Comment by ywk253100** [comment]
Both `registry` and `registryctl` needs to access the registry storage volume, the registryctl cannot start up if the volume doesn't support RWM

**Comment by holyhope** [comment]
It needs to access to the same volume if registry is configured with a FS driver.
It needs to be in the same node if PV does not support RWM.
Is there some case where it requires to be in the same pod?

**Comment by steven-zou** [comment]
> It needs to access to the same volume if registry is configured with a FS driver.
> It needs to be in the same node if PV does not support RWM.
> What are cases which require registry and registryctl to be in the same pod?

VMware Pod VM.

**Comment by steven-zou** [comment]
> I am seeing random instances where the registry and registryctl pods get scheduled to different nodes (despite the pod affinity of the registryctl pod the scheduler is free to do so). For many storage drivers this will prevent one of the pods to start up because the volume is already bound to another node.
> 
> So to be honest I'd even think about classifying this issue as a bug, as it can arbitrarily prevent proper startup of vital components. What's your view on this, @steven-zou ?
> 
> Putting both components in the same pod would solve this problem quite elegantly. Are there any technical reasons that stand against a single-pod deployment of them?

@dajudge 

Thanks for commenting here.


I don't think there are some technical reasons that stand against a single-pod deployment of them. @holyhope has some preferences before. Actually, we're considering putting those two containers into one pod deployment to support a more wide use case list, and also registry and registrctl really share similar configurations.  Putting them into one pod will make container/pod configuration simpler.
