### ISSUE TITLE
Replication failed x509 error when redirect is true

### ISSUE THREAD

**Issue by chlins** [goharbor/harbor-operator#347]
What can we help you?

![image](https://user-images.githubusercontent.com/31262637/102468726-dfd7e800-408c-11eb-97de-a12bc84b52e5.png)

**Comment by chlins** [comment]
After inject sample-public-certs to  core and jobsevice pod. It woks.

![image](https://user-images.githubusercontent.com/31262637/102973951-a7c32000-4538-11eb-8b0e-ccb664ad0e6d.png)

**Comment by steven-zou** [comment]
- [ ]  Core
- [ ] JS
- [ ] Trivy

Inject ca to the above components

**Comment by holyhope** [comment]
Hello
FYI certmanager project has a csi to inject _properly_ certificates: https://cert-manager.io/v0.16-docs/usage/csi/
WDYT about using it?

**Comment by bitsf** [comment]
@holyhope csi seems apply to handling internal tls creating, while current issue is just need to inject the harbor public cert into some pods' special folder, I'm afraid CSI can't work for it

**Comment by steven-zou** [comment]
And it's also an experimental feature. @holyhope 

But it seems to be useful for distributing Harbor cert to all the nodes where the scheduled pods are running.
