### ISSUE TITLE
Re-apply HarborCluster resource does not affect the minio resource when minio not ready

### ISSUE THREAD

**Issue by heww** [goharbor/harbor-operator#375]
**Steps to reproduce the problem:**

Deploy the harbor-operator with custom minio image `HARBORCLUSTER_STORAGE_IMAGE=quay.io/goharbor/minio:RELEASE.2020-08-13T02-39-50Z`

1. Apply the full_stack.yaml
2. The minio pod will not ready due to the pull rate limitation of the dockerhub
3. Remove the version field in the minIOSpec of full_stack.yaml so that the harbor operator can change to use the minio image provide by the HARBORCLUSTER_STORAGE_IMAGE env.
4. Re-apply the full_stack.yaml

**Expected behavior and actual behavior:**
Want the minio pods were removed and use the image from quay.io, but they are still pending in ImagePullBackOff status

**Comment by steven-zou** [comment]
re-apply minio does not work.

**Comment by wangcanfengxs** [comment]
> Remove the version field in the minIOSpec of full_stack.yaml so that the harbor operator can change to use the minio image provide by the HARBORCLUSTER_STORAGE_IMAGE env.

There is no version field in the minIOSpec now.

**Comment by wangcanfengxs** [comment]
If old minioCR set some filed but remove in the new minioCR, it will not do reconcile because of 
```
equality.Semantic.DeepEqual(old, new)
```
