### ISSUE TITLE
The pv/pvc of minio not deleted after the harbor cluster deleted

### ISSUE THREAD

**Issue by heww** [goharbor/harbor-operator#394]
Create a harbor cluster with incluster Postgres, Redis and Minio, delete the harbor cluster after it's healthy. The result is that the pv/pvc of postgres, redis will be deleted, but the minio's will not.

**Comment by steven-zou** [comment]
if the PV of the  Postgres, Redis are deleted, the database will be lost. It seems the PVs should also be kept.

**Comment by steven-zou** [comment]
@Ghostbaby @chlins 

Let's keep consistent behavior:  **all not delete**

**Comment by Ghostbaby** [comment]
@steven-zou Postgres operator is not supported to keep PVC.

**Comment by steven-zou** [comment]
@Ghostbaby 

Do we have any workaround to resolve the problem as we have a very tight timeline now?

**Comment by steven-zou** [comment]
For keeping consistency, all the PVs will be deleted after the Harbor cluster is deleted.

@chlins / @soulseen 

- [ x] PostgreSQL: default behavior
- [  ] Redis
- [  ] MINIO
