### ISSUE TITLE
Issue found in the Harbor class

### ISSUE THREAD

**Issue by steven-zou** [goharbor/harbor-operator#399]

**Comment by holyhope** [comment]
When using harbor-class annotation, controllers do not watch the right resources.
Add tests for watching resources with owner with harbor-class.

_Suggestion:_ When running tests, generate a harbor class name so multiple controllers may be started at the same time.

**Comment by holyhope** [comment]
### Related packages

- https://github.com/goharbor/harbor-operator/tree/master/pkg/event-filter/class
- https://github.com/goharbor/harbor-operator/blob/master/controllers/goharbor/chartmuseum/chartmuseum.go#L77-L79
  (Same code in others controllers)

### More information

The top-level resource (such as Harbor) is filtered with the annotation, what about child resources? Those children do not have annotation.
