### ISSUE TITLE
dump the commit ID in the log

### ISSUE THREAD

**Issue by reasonerjt** [goharbor/harbor-operator#400]
There should be a way to help the consumers identify the version of the operator they are using.

Please consider dump the commit ID in all or some components to help user debug

**Comment by steven-zou** [comment]
add version/commitid to the print columns of kubectl get harborcluster

**Comment by steven-zou** [comment]
`// Log
	setupLog.Info("starting manager", "version", version, "commit", commit)`

When the operator is started, the version/commit has been dumped to the log.

**Comment by heww** [comment]
Closed by #482
