### ISSUE TITLE
db connection seems not stable 

### ISSUE THREAD

**Issue by bitsf** [goharbor/harbor-operator#401]
sometimes I can see db connection error in harbor-core log
![image](https://user-images.githubusercontent.com/188115/104981838-5a0cdb00-5a44-11eb-87c7-272dda2f6029.png)

describe harbor-core
![image](https://user-images.githubusercontent.com/188115/104981997-a9530b80-5a44-11eb-8de6-9fc6143726d3.png)

log postgres
![image](https://user-images.githubusercontent.com/188115/104982245-37c78d00-5a45-11eb-858c-c72e44546842.png)

**Comment by steven-zou** [comment]
Now, the issue has been eliminated.
