### ISSUE TITLE
s3.regionendpoint doesn't have schema

### ISSUE THREAD

**Issue by bitsf** [goharbor/harbor-operator#451]
commit: 898cdc88e527638a666e3305ae68e60f1bcea773

1. patch spec.imageChartStorage.s3.certificateRef first as issue https://github.com/goharbor/harbor-operator/issues/450
```
diff --git a/apis/goharbor.io/v1alpha2/registry_types.go b/apis/goharbor.io/v1alpha2/registry_typ
es.go
index 13a1dfa1..4162fb22 100644
--- a/apis/goharbor.io/v1alpha2/registry_types.go
+++ b/apis/goharbor.io/v1alpha2/registry_types.go
@@ -710,7 +710,7 @@ type RegistryStorageDriverS3Spec struct {
 
        // +kubebuilder:validation:Optional
        // +kubebuilder:validation:Pattern="[a-z0-9]([-a-z0-9]*[a-z0-9])?(\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*"
-       CertificateRef string `json:"certificateRef"`
+       CertificateRef string `json:"certificateRef,omitempty"`
 
        // +kubebuilder:validation:Optional
        // +kubebuilder:default=true
```

2. install harbor with `manifests/samples/full_stack.yaml`
3. kubectl get cm harborcluster-sample-harbor-harbor-registry -o jsonpath='{.binaryData.config\.yml}' | base64 -d
![image](https://user-images.githubusercontent.com/188115/108595184-6aa0d000-73b9-11eb-971d-daba0afcb1a5.png)

**Comment by steven-zou** [comment]
Now, it's `HTTPS`.

I think we can use ToLowerCase(r.getSchema()) to refine it. cc @soulseen

**Comment by steven-zou** [comment]
the issue has been resolved now
