### ISSUE TITLE
the default region for minio should not be us-east-1

### ISSUE THREAD

**Issue by bitsf** [goharbor/harbor-operator#452]
the DefaultRegion defined in pkg/cluster/controllers/storage/minio.go:29 is `us-east-1`, this is not a good name, maybe we can name it as `default`

**Comment by steven-zou** [comment]
I guess this is a default value of minio. @soulseen

**Comment by bitsf** [comment]
this is just hard code in our code

**Comment by soulseen** [comment]
`us-east-1`  is the default Region for s3 API calls
