### ISSUE TITLE
install jetstack/cert-manager 0.15 in CI is always failed

### ISSUE THREAD

**Issue by bitsf** [goharbor/harbor-operator#46]
![image](https://user-images.githubusercontent.com/188115/78893638-40df0300-7a9e-11ea-95f4-f575c910398e.png)

![image](https://user-images.githubusercontent.com/188115/78893805-87346200-7a9e-11ea-9c20-c5ad07a9d5f4.png)

**Comment by steven-zou** [comment]
@holyhope 

Any clues for this CI/CD issue?

**Comment by holyhope** [comment]
Indeed files have been moved:
<https://github.com/jetstack/cert-manager/blob/release-0.15/deploy/manifests/README.md#where-are-the-manifests-now>
