### ISSUE TITLE
dns name can not be updated

### ISSUE THREAD

**Issue by bitsf** [goharbor/harbor-operator#469]
1. install harbor with dns name `core.harbor.domain` and `notary.harbor.domain` with manifests/samples/full_stack_other_fs.yaml
2. update harbor with dns name `core.10.182.178.34.nip.io` and `notary.10.182.178.34.nip.io`
3. `core.10.182.178.34.nip.io` does not take effect
![image](https://user-images.githubusercontent.com/188115/109909502-2da1db00-7ce1-11eb-9191-68c6326b9407.png)

**Comment by steven-zou** [comment]
any log in the controller?

**Comment by steven-zou** [comment]
code:

```
// Found the existing one and check whether it needs to be updated
	desiredCR := harbor.getHarborCR(harborcluster)

	same := equality.Semantic.DeepDerivative(desiredCR.Spec, harborCR.Spec)
	if !same {
		// Spec is changed, do update now
		harbor.Log.Info("update harbor service", "name", nsdName)

		harborCR.Spec = desiredCR.Spec
		if err := harbor.KubeClient.Update(harborCR); err != nil {
			return harborNotReadyStatus(UpdateHarborCRError, err.Error()), err
		}
	}
```

**Comment by bitsf** [comment]
should be fixed by check Immutable Resource
