### ISSUE TITLE
k8s 1.18 can not be support now

### ISSUE THREAD

**Issue by bitsf** [goharbor/harbor-operator#471]
test commit: d9d1af8af32884817c13be31bcc0bd9c802073a6

k8s 1.18 can not be support now
error `2021-03-04T06:14:08.382Z        ERROR   setup   cannot start manager    {"error": "no matches for kind \"Ingress\" in version \"networking.k8s.io/v1\""}`
![image](https://user-images.githubusercontent.com/188115/109919983-8d55b180-7cf4-11eb-8637-b83a909bcca0.png)

![image](https://user-images.githubusercontent.com/188115/109919917-76af5a80-7cf4-11eb-8d93-88f8ec8ae78d.png)

https://github.com/goharbor/harbor-operator/actions/runs/619774266

**Comment by steven-zou** [comment]
Fixes by https://github.com/goharbor/harbor-operator/pull/454
