### ISSUE TITLE
Migrate Harbor version to V2.2

### ISSUE THREAD

**Issue by steven-zou** [goharbor/harbor-operator#481]
New container metrics exporter has been introduced

**Comment by steven-zou** [comment]
@holyhope 

A draft design is shown here: https://miro.com/app/board/o9J_lPPAolU=/ . The exporter will be a separate pod then.

**Comment by steven-zou** [comment]
@holyhope 

If you have not enough time to deliver it ASAP, @heww can help to do this work. What do you think?

**Comment by heww** [comment]
Closed by https://github.com/goharbor/harbor-operator/pull/525
