### ISSUE TITLE
add operator configmap into kustomization manifests

### ISSUE THREAD

**Issue by steven-zou** [goharbor/harbor-operator#517]
References: charts/harbor-operator/templates/configmap.yaml

**Comment by bitsf** [comment]
error message in harbor-operator
`2021-04-12T11:40:52.839Z        ERROR   setup.jobservice        invalid config file     {"error": "stat /etc/harbor-operator/jobservice-ctrl.yaml: no such file or directory"}`

![image](https://user-images.githubusercontent.com/188115/114389854-1d2a2d80-9bc8-11eb-829a-b9343fd8ea49.png)
