### ISSUE TITLE
Status in `kubectl describe harborcluster harborcluster-sample` and `kubectl get harborcluster harborcluster-sample -o wide` are not same

### ISSUE THREAD

**Issue by bitsf** [goharbor/harbor-operator#530]
Status in `kubectl describe harborcluster harborcluster-sample` and `kubectl get harborcluster harborcluster-sample -o wide` are not same
![image](https://user-images.githubusercontent.com/188115/113680779-d209a980-96f3-11eb-9285-345e383abf5c.png)

**Comment by heww** [comment]
Yes, not all the conditions are displayed in the wide output.
