### ISSUE TITLE
What helm version supported in install-with-kind-k8s.md

### ISSUE THREAD

**Issue by wangcanfengxs** [goharbor/harbor-operator#57]
when I run 
`helm install cert-manager jetstack/cert-manager --namespace cert-manager --version v0.13.1
`
It return error
`Error: This command needs 1 argument: chart name`

I use helm v2.16.8.
The reason is that helm install only need one argument to specify chart name, any others are flags.
So I changed the command to 
`helm install --name cert-manager jetstack/cert-manager --namespace cert-manager --version v0.13.1
`
It works.

**Comment by steven-zou** [comment]
Issue is outdated
