### ISSUE TITLE
Wrong secret name referenced when using inClusterDatabase

### ISSUE THREAD

**Issue by dajudge** [goharbor/harbor-operator#572]
**Expected behavior and actual behavior:**
I'm trying to create a harbor cluster with `inClusterDatabase` enabled. After creating the PostgreSQL database using the Zalando PostgresSQL Operator, the harbor-operator seems to try to lookup a secret named `harbor.postgresql-harbor-harborcluster-sample.credentials` where the actual secret created by the zalando operator has a suffix `.postgresql.acid.zalan.do` and is thus named `harbor.postgresql-harbor-harborcluster-sample.credentials.postgresql.acid.zalan.do`.

Relevant log entry:
```
2021-04-19T16:10:15.522Z	ERROR	controller	Reconciler error	{"reconcilerGroup": "goharbor.io", "reconcilerKind": "HarborCluster", "controller": "harborcluster", "name": "harborcluster-sample", "namespace": "harbor", "error": "reconcile dependent services error: gos.Group error: Secret \"harbor.postgresql-harbor-harborcluster-sample.credentials\" not found"}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.2/pkg/internal/controller/controller.go:209
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.2/pkg/internal/controller/controller.go:188
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1
	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:155
k8s.io/apimachinery/pkg/util/wait.BackoffUntil
	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:156
k8s.io/apimachinery/pkg/util/wait.JitterUntil
	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:133
k8s.io/apimachinery/pkg/util/wait.Until
	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:90
```

**Steps to reproduce the problem:**
1. Install redis-operator, postgresql-operator, certmanager
2. Install harbor-operator
3. Install sample from `https://github.com/goharbor/harbor-operator/blob/master/manifests/samples/harbor_core_fs.yaml`

**Versions:**
- harbor operator version: dev_master (docker image)
- harbor version: 2.2.1
- kubernetes version: 1.20.2
- postgres-operator: 1.6.2

**Comment by dajudge** [comment]
Looking at the test results of #575 I'm wondering: might this be a difference between Zalando PostgreSQL Operator versions? From what I've pieced together I believe the tests are running w/ v1.5.0 where I'm running v1.6.2 locally...

**Comment by dajudge** [comment]
I think I got a little closer here: the way you install the Zalando PostgreSQL operator during tests (via kustomize) uses a configuration where 

`secret_name_template: '{username}.{cluster}.credentials'`

while a deployment via helm chart e.g. seems to default to

`secret_name_template: '{username}.{cluster}.credentials.{tprkind}.{tprgroup}'`

So I guess in order to accommodate different postgres-operator configurations out there it would be preferable to support both use-cases?

**Comment by dajudge** [comment]
The piece of code in the postgres-operator responsible to building the secret name is here: https://github.com/zalando/postgres-operator/blob/0745ce7cce63ab6431103d27eb08e54ec47d2b15/pkg/cluster/util.go#L514

I'll have a look into adopting the same semantics for the harbor-operator

**Comment by steven-zou** [comment]
@dajudge 

Thanks a lot for raising the issue and trying to fix it. I saw the PR is still in `Draft` status, when can it be ready?

@Ghostbaby would you please double confirm this issue?

**Comment by Ghostbaby** [comment]
@steven-zou copy

**Comment by steven-zou** [comment]
@dajudge 

Agree. We need to use the same secret pattern to fit all the cases: installed with customization provided by harbor-operator or operator helm chart provided by Zalando. cc @Ghostbaby

**Comment by dajudge** [comment]
> One more question for you @dajudge, why not try to use the all-in-one Kustomization to deploy the operator? Any considerations?

@steven-zou it's not so much kustomize vs. helm for us. we already have several postgres DBs running for several tenants - we can't just change the secret-naming convention now :-)

> Thanks a lot for raising the issue and trying to fix it. I saw the PR is still in Draft status, when can it be ready?

@steven-zou  I'll have a look at the remaining issues (as far as I can see it's only lint errors by now) and then un-draft the PR. Please let me know what you're going to need beyond the actual implementation.
