### ISSUE TITLE
sometimes CI failed because harborcluster-sample-harbor-harbor-notarysigner-authority not ready

### ISSUE THREAD

**Issue by bitsf** [goharbor/harbor-operator#592]
https://github.com/goharbor/harbor-operator/pull/583/checks?check_run_id=2400534324
![image](https://user-images.githubusercontent.com/188115/115649581-29e21a80-a35a-11eb-8af4-0c125b7cd253.png)
![image](https://user-images.githubusercontent.com/188115/115651334-898df500-a35d-11eb-980e-42e48ac446c3.png)
kubectl describe harbor-operator
![image](https://user-images.githubusercontent.com/188115/115651869-a7a82500-a35e-11eb-86b8-f88128851656.png)
harbor-operator log
![image](https://user-images.githubusercontent.com/188115/115651902-ba225e80-a35e-11eb-9104-3aea3ecbc976.png)
![image](https://user-images.githubusercontent.com/188115/115651946-d4f4d300-a35e-11eb-8a63-722434d4a3fa.png)

**Comment by steven-zou** [comment]
@bitsf 
Could we have a try to fix it in the upcoming 1.0.1?

**Comment by bitsf** [comment]
kubectl -n cluster-sample-ns get cert -o wide
![image](https://user-images.githubusercontent.com/188115/118584248-29a63500-b7c9-11eb-9c84-577a49b4a90f.png)

kubectl -n cluster-sample-ns get certificaterequests -o wide
![image](https://user-images.githubusercontent.com/188115/118584332-4f333e80-b7c9-11eb-9630-d3ce1a88e800.png)

can't reproduced locally

**Comment by steven-zou** [comment]
Same root cause with #533
