### ISSUE TITLE
The redis secret is hardcoded in the chartmuseum

### ISSUE THREAD

**Issue by stonezdj** [goharbor/harbor-operator#604]
After deploy the harbor operator and deploy harbor with external database and redis, my redis secret 
 is redissec, it is specified in manifest file, but the chartmuseum container still failed with the following error:
```
  Warning  Failed                  21s (x12 over 2m30s)  kubelet                  Error: secret "harbor-redis" not found
```

It seems that the secret of redis in chartmuseum is hardcoded.

**Comment by bitsf** [comment]
![image](https://user-images.githubusercontent.com/188115/116243225-51414900-a799-11eb-964a-b6c744de794f.png)
I just got error `Error: couldn't find key redis-password in Secret default/harbor-redis12`

**Comment by bitsf** [comment]
@stonezdj I think you didn't change passwordRef in harborcluster_standard_stack_external.yaml

**Comment by stonezdj** [comment]
can not reproduce it
