### ISSUE TITLE
How to upgrade the depended CRs?

### ISSUE THREAD

**Issue by reasonerjt** [goharbor/harbor-operator#633]
This doc briefly covered how to upgrade Harbor instance by updating the `.spec.version`:
https://github.com/goharbor/harbor-operator/blob/master/docs/LCM/upgrade-cluster.md

Since we allow users to install Redis/pgSQL/Minio operators along with harbor-operator in an all-in-one approach.  We should provide a solution for user to update the depended services?

**Comment by bitsf** [comment]
we update the dependencies with harbor-operator upgrade
