### ISSUE TITLE
Make the deployment of Portal optional

### ISSUE THREAD

**Issue by sguyennet** [goharbor/harbor-operator#645]
Sometime user do not want to deploy Portal.
At the moment there is no way in the Harbor CR to tell the operator not to deploy Portal.

**Comment by steven-zou** [comment]
@sguyennet 

It seems to support this feature we need to do modifications of CRD, right? As there are other changes required to do CRD modifications in the coming 1.1 release, I put this issue from 1.2 to the 1.1 release. 1.1 is planned to release in mid of June. Is that ok?

**Comment by Thrimbda** [comment]
along with Portal deployment, some of the ingress rule are not needed in some use cases, can we make the harbor ingress rule configurable as well?

**Comment by steven-zou** [comment]
Per resource limitation, this work needs to be moved to release 1.2.
