### ISSUE TITLE
Expose additional configuration options for S3 storage

### ISSUE THREAD

**Issue by 0x442E472E** [goharbor/harbor-operator#676]
**Is your feature request related to a problem? Please describe.**
The used implementation for S3 has problems with some S3 backends, like this: https://github.com/goharbor/harbor/issues/12317

The proposed mitigation from that ticket does not work with the harbor operator, because the CRD does not allow setting multipartcopythresholdsize. Patching the ConfigMap for the registry pod does resolve the issue, but that's no sustainable solution.

**Describe the solution you'd like**
I would like to set multipartcopythresholdsize and other S3 settings via the CR.

**Comment by steven-zou** [comment]
Change reference: https://github.com/goharbor/harbor-helm/commit/35c746ca292e33433ded0c0cd1aa51c0672638a8
