### ISSUE TITLE
cert-manager 1.4.0 not support

### ISSUE THREAD

**Issue by bitsf** [goharbor/harbor-operator#693]
can't install harbor successfully when using cert-manager 1.4.0
harborcluster-sample-harbor-harbor-notarysigner-authentication: not ready
![image](https://user-images.githubusercontent.com/188115/123961940-7a719600-d9e3-11eb-91c4-e6c6a29a7263.png)
![image](https://user-images.githubusercontent.com/188115/123962034-96753780-d9e3-11eb-9cbb-5f0f578a3800.png)

**Comment by bitsf** [comment]
`kubectl get cert harborcluster-sample-harbor-harbor-notarysigner-authentication -o yaml` shows error 
`message: 'The certificate request has failed to complete and will be retried: Failed to decode returned certificate: error decoding certificate PEM block'`

this seems an issue of https://github.com/jetstack/cert-manager/issues/4142

when change common name `harborcluster-sample-harbor-harbor-notarysigner` of cert, it will be good.

**Comment by maelvls** [comment]
Hi! Just FYI, cert-manager 1.4.1 was released with a fix for this issue.
