### ISSUE TITLE
is forbidden: cannot set blockOwnerDeletion if an ownerReference refers to a resource you can''t set finalizers on: , <nil>'       reason: Create harbor.goharbor.io CR error

### ISSUE THREAD

**Issue by jorgemansillacriado** [goharbor/harbor-operator#698]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
I have next error when I try to do apply 

is forbidden: cannot set blockOwnerDeletion if an ownerReference refers to a resource you can''t set finalizers on: , <nil>'
      reason: Create harbor.goharbor.io CR error
status:
    conditions:
    - lastTransitionTime: "2021-07-06T07:37:03Z"
      status: "True"
      type: StorageReady
    - lastTransitionTime: "2021-07-06T07:37:03Z"
      status: "True"
      type: DatabaseReady
    - lastTransitionTime: "2021-07-06T07:37:03Z"
      status: "True"
      type: CacheReady
    - lastTransitionTime: "2021-07-06T07:37:03Z"
      message: 'harbors.goharbor.io "sample-harbor" is forbidden: cannot set blockOwnerDeletion if an ownerReference refers to a resource you can''t set finalizers on: , <nil>'
      reason: Create harbor.goharbor.io CR error
      status: "False"
      type: ServiceReady

**Steps to reproduce the problem:**
kubectl apply -f 

**Versions:**
Please specify the versions of following systems.

- harbor operator version: latest
- harbor version: 2.2.1
- kubernetes version: [v1.19.0+a5a0987
- Any additional relevant versions such as CertManager

**Additional context:**

- **Harbor dependent services:**
  - Context info of postgreSQL
  - Context info of Redis
  - Context info of storage
- **Log files:** Collect logs and attach them here if have.
- **Kubernetes:** How Kubernetes access was provided (what cloud provider, service-account configuration, ...).

**Comment by cndoit18** [comment]
Is your version of harbor-operator v1.0.1? I may need more information to help me locate the problem. thank you

**Comment by cndoit18** [comment]
I've observed other similar feedback on this issue, It seems to be because of the deployment on openshift. are you also deploying on openshift

**Comment by jorgemansillacriado** [comment]
Hi 

harbor-operator is v1.0.1

**Comment by jorgemansillacriado** [comment]
Yes, we're using openshift 4.6

**Comment by steven-zou** [comment]
@jorgemansillacriado 

As it's hard for us to prepare an openshift planform, I'm wondering is it possible to use your platform to verify a patch provided by @cndoit18 later?

**Comment by jorgemansillacriado** [comment]
yes I can probe in my platform don't worry

please give path and I can probe it

**Comment by cndoit18** [comment]
Thank you very much, I will provide it here a little later

**Comment by KaiReichart** [comment]
We have exactly the same issue, but also with the dependent operators. Also more than willing to help/try any patches.

Our Error Messages:
```
    - lastTransitionTime: '2021-07-23T13:31:00Z'
      message: >-
        tenants.minio.min.io "minio-harborcluster-sample" is forbidden: cannot
        set blockOwnerDeletion if an ownerReference refers to a resource you
        can't set finalizers on: , <nil>
      reason: create minIO CR error
      status: 'False'
      type: StorageReady
    - lastTransitionTime: '2021-07-23T13:31:00Z'
      message: >-
        postgresqls.acid.zalan.do
        "postgresql-cao-argocd-harbor-harborcluster-sample" is forbidden: cannot
        set blockOwnerDeletion if an ownerReference refers to a resource you
        can't set finalizers on: , <nil>
      reason: Create database CR error
      status: 'False'
      type: DatabaseReady
    - lastTransitionTime: '2021-07-23T13:31:00Z'
      message: >-
        secrets "harborcluster-sample-redis" is forbidden: cannot set
        blockOwnerDeletion if an ownerReference refers to a resource you can't
        set finalizers on: , <nil>
      reason: Create redis secret error
      status: 'False'
      type: CacheReady
    - message: New generation detected
      reason: newGeneration
      status: 'True'
      type: InProgress
```

On OpenShift v4.7.7 and Operator Version 1.0.1

**Comment by cndoit18** [comment]
I have provided a solution, can you help me to verify it? Thank you @KaiReichart @jorgemansillacriado

**Comment by jorgemansillacriado** [comment]
Hi

I have probe new fix but I have other error, I have same message with every examples
Error from server (MethodNotAllowed): error when creating "minimal_stack_fs.yaml": create not allowed while custom resource definition is terminating

**Comment by bitsf** [comment]
@jorgemansillacriado it seems you didn't finish cleanup old resources before apply new. you can delete the namespace first.
yamls in manifests/samples are good to use, our CI is just them.
