### ISSUE TITLE
Missing the harbor cluster ref for the harbor configuration spec

### ISSUE THREAD

**Issue by heww** [goharbor/harbor-operator#724]
There isn't a way to tell harbor configuration which harbor cluster will be applied for the configuration.

In harbor operator 1.0, we use the config map for the harbor configuration and we need to ref the harbor cluster in the annotations. Now we have a cr to implement the harbor configuration, I think we need to ref the harbor cluster in the spec of the harbor configuration cr.

**Comment by bitsf** [comment]
refactor the harbor_configure model, add namespace
