### ISSUE TITLE
Does it support  Kubenetes  1.21  version  to deploy Harbor operator by Helm chart

### ISSUE THREAD

**Issue by LaryCaka** [goharbor/harbor-operator#727]
Does it support  Kubenetes  1.21  version  to deploy Harbor operator by Helm chart
![image](https://user-images.githubusercontent.com/32317315/127251058-e064444f-f00d-495c-b170-98d050bfd877.png)

**Comment by cndoit18** [comment]
https://github.com/goharbor/harbor-operator/blob/master/docs/installation/by-helm-chart.md
