### ISSUE TITLE
failed to install on openshift cluster

### ISSUE THREAD

**Issue by bitsf** [goharbor/harbor-operator#758]
error info
```
Status:
 Conditions:
   Last Transition Time: 2021-08-25T13:18:32Z
   Status:               True
   Type:                 StorageReady
   Last Transition Time: 2021-08-25T13:18:32Z
   Message:              secrets "harborcluster-sample-redis" is forbidden: cannot set blockOwnerDeletion if an ownerReference refers to a resource you can't set finalizers on: , <nil>
   Reason:               Create redis secret error
   Status:               False
   Type:                 CacheReady
   Last Transition Time: 2021-08-25T13:18:32Z
   Message:               postgresqls.acid.zalan.do "postgresql-cluster-sample-ns-harborcluster-sample" is forbidden: cannot set blockOwnerDeletion if an ownerReference refers to a resource you can't set finalizers on: , <nil>
   Reason:               Create database CR error
   Status:               False
   Type:                 DatabaseReady
   Message:              New generation detected
   Reason:               newGeneration
   Status:               True
   Type:                 InProgress
```

steps to install openshift 3.x
- prepare Centos 7
- yum install -y wget git ntp net-tools bind-utils iptables-services bridge-utils bash-completion kexec-tools sos psacct nfs-utils yum-utils docker NetworkManager pyOpenSSL httpd-tools python-cryptography python-lxml skopeo origin-docker-excluder centos-release-ansible-29 ansible
- git clone https://github.com/openshift/openshift-ansible -b release-3.11
- cd openshift-ansible
- sudo ansible-playbook -i inventory/hosts.localhost playbooks/prerequisites.yml
- sudo ansible-playbook -i inventory/hosts.localhost playbooks/deploy_cluster.yml

**Comment by holyhope** [comment]
Hello people,

We could add any needed resources to the helm chart with a [capability condition](https://helm.sh/docs/chart_template_guide/function_list/#capabilitiesapiversionshas). So these resources is only installed on OpenShift clusters and not on raw clusters.

The only pain point is finding resources that must be added to the chart. :-)
