### ISSUE TITLE
Image tag never falls back to app version

### ISSUE THREAD

**Issue by sagikazarmark** [goharbor/harbor-operator#764]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
When installing the latest stable Helm chart from the releases page, the operator pod ends up in a crash loop, complaining about missing configuration.

**Steps to reproduce the problem:**
Download the latest stable chart
Install it with default values

**Versions:**
Please specify the versions of following systems.

- harbor operator version: 1.1.0
- harbor version: any
- kubernetes version: 1.21
- Any additional relevant versions such as CertManager

**Additional context:**

The problem seems to be the `image.tag` variable which is set to `dev`. The documentation claims that it would fallback to the `.Chart.AppVersion` variable, but in fact that never happens because `image.tag` is already set.

`image.tag` should probably be empty by default.

**Comment by bitsf** [comment]
ok, will check this problem

**Comment by bitsf** [comment]
update harbor-operator-v1.1.0.tgz
