### ISSUE TITLE
upgrade minio

### ISSUE THREAD

**Issue by bitsf** [goharbor/harbor-operator#777]
1. upgrade minio-operator, like v4.2.10
2. upgrade minio, like RELEASE.2021-09-23T04-46-24Z
3. upgrade minio-console, like v0.10.1

**Comment by ron1** [comment]
Note the use of spec.users and spec.configuration.name and also the depreciation of spec.credsSecret here: https://github.com/minio/operator/blob/31460bbbc4b7bd3f24ed41c73e9e5dfdc73eacf6/examples/kustomization/base/tenant.yaml#L41
