### ISSUE TITLE
Split components into multiple CRD/controllers

### ISSUE THREAD

**Issue by holyhope** [goharbor/harbor-operator#8]
Split the Harbor CRD into multiple smaller one.
So every components can be reconciled independently.

Have a definition for following components
- `ChartMuseum`
- `Clair`
- `Core`
- `JobService`
- `NotaryServer`
- `NotarySigner`
- `Portal`
- `Registry`
- `RegistryController`

And an other definition `Harbor` which can handle all of them.

BTW with multiple controllers this would reconcile faster.

**Comment by steven-zou** [comment]
Work has been done!
