### ISSUE TITLE
Trivy scanner not removed after remove trivy component.

### ISSUE THREAD

**Issue by chlins** [goharbor/harbor-operator#825]
What can we help you?

Deploy `full_stack` harborcluster and the trivy scanner was not removed after removing trivy component, does this behavior by design? 

![image](https://user-images.githubusercontent.com/31262637/145531625-79e7b14c-db56-4271-9e45-23e0dd4f8eb1.png)

**Comment by bitsf** [comment]
there's an env of core pod should also be removed
