### ISSUE TITLE
Specify notary signer database encryption key secret in CR

### ISSUE THREAD

**Issue by thcdrt** [goharbor/harbor-operator#850]
Hello,

Currently, notary signer encryption key used to encrypt privates keys in notary signer database is auto generated [here](https://github.com/goharbor/harbor-operator/blob/master/controllers/goharbor/harbor/notarysigner.go#L124).

This key is not stored anywhere, if the secret `notarysigner-encryption-key` is deleted, the encryption key is lost forever and the private keys stored in notary signer databases are lost too.

Why not add the possibility to give a secret name in harborclusters/notary CR ?

WDYT ?

Thomas

**Comment by bitsf** [comment]
notary is to be deprecated as it is not actively maintained. we will introduce cosign to sign the images in harbor 2.5.
So this feature will not be supported
