### ISSUE TITLE
sign off release 1.3.0

### ISSUE THREAD

**Issue by bitsf** [goharbor/harbor-operator#901]
please maintainers help test harbor-operator 1.3.0 rc build, and sign off here
- [ ] Steven Zou , steven-zou , VMware
- [x] Ziming Zhang , bitsf , VMware
- [x] Weiwei He , heww, VMware
- [x] Chengyu Zhang , chlins , VMware
- [ ] Yinan Li , cndoit18 , ByteDance
- [x] Xiongxiong Yuan, yxxhero, GitLab.cn
- [ ] Xiaoyang Zhu , soulseen , Shoppee
- [ ] Canfeng Wang , wangcanfengxs , Netease

**Comment by yxxhero** [comment]
1. minio can't upgrade in-place.
```bash
Error: UPGRADE FAILED: cannot patch "minio-operator" with kind Deployment: Deployment.apps "minio-operator" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"app.kubernetes.io/instance":"harbor-operator", "app.kubernetes.io/name":"operator"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable
```
related: 
* https://github.com/minio/operator/commit/dd62a262d168474692785cb8e4c6524133b38dee#diff-bd5c6c9ae089d94d6ca2bec730b2f1e92357842567d49c4dd44123ef65986244
* https://github.com/goharbor/harbor-operator/commit/95a56f37f943c9c67261ab542776c7a5cc8e855b
