### ISSUE TITLE
image pull  problem

### ISSUE THREAD

**Issue by QiuToo** [goharbor/harbor-operator#920]
I'm dying to know, ghcr Where is the image of io/goharbor placed? I have taken ghcr in China io/goharbor/minio:RELEASE. The 2021-07-27t02-40-15z image took me more than an hour, but the image is not large
===
Harbor-Operator  Version： v1.1.2

**Comment by bitsf** [comment]
hi , I didn't find any problem to run `docker pull ghcr.io/goharbor/minio:release.2021-07-27t02-40-15z` in China
