### ISSUE TITLE
Deploy it to openshift

### ISSUE THREAD

**Issue by shichw** [goharbor/harbor-operator#927]
Excuse me, how to use harbor-operator to deploy harbor cluster to openshift in a full-stack manner.

**Comment by bitsf** [comment]
hi, we don't hav openshift to test yet, but it should just be same as other k8s cluster.
- kubectl apply -f https://raw.githubusercontent.com/goharbor/harbor-operator/v1.3.0/manifests/cluster/deployment.yaml
- wget https://raw.githubusercontent.com/goharbor/harbor-operator/v1.3.0/manifests/samples/full_stack.yaml
- edit hostname in full_stack.yaml
- kubectl apply -f full_stack.yaml

if you find issue, you can collect logs and report
