### ISSUE TITLE
It is recommended that the `expost.core.ingress` field be changed to optional

### ISSUE THREAD

**Issue by lengrongfu** [goharbor/harbor-operator#955]
What can we help you?

Currently `ExternalURL` and `expost.core.ingress` fields are required, can they be changed to not required?
Currently we have a scenario where we only need to access the `Harbor` backend service, and it is accessed inside the `k8s` cluster, so it can be accessed through the `service ClusterIp type` of `harbor core`.

**Comment by heww** [comment]
`ExternalURL` is a required configuration for the harbor-core because the harbor-core uses this configuration to generate the auth service URL.

ingress can be changed to not required

**Comment by thcdrt** [comment]
Fixed in #975
