### ISSUE TITLE
Move `TrivyStorage` to the trivy component?

### ISSUE THREAD

**Issue by steven-zou** [goharbor/harbor-operator#96]
`TrivyStorage *HarborStorageTrivyStorageSpec `json:"trivyStorage,omitempty"``

It is a temp storage for trivy to hold CVE DB and is more close to Trivy component itself. Maybe it's better and more clear to put it under the trivy component.

**Comment by holyhope** [comment]
I will also move `ImageChartStorage` under `spec.regstry`
