### ISSUE TITLE
Rename `HarborHelm1_4_0Spec` to a more general one?

### ISSUE THREAD

**Issue by steven-zou** [goharbor/harbor-operator#97]
I understand the current operator spec is referring to the harbor chart V1.4 templates.

My concern is anyway those two specs will be developed separately in the future. Some configuration may be introduced into the operator spec but not put into the chart template. And If the chart version is upgrading or templates are changed for fixing some bugs in the chart and maybe no influences to the operator, will the operator define a new spec object `HarborHelm1_5_0Spec` then?

**Comment by steven-zou** [comment]
cc @holyhope

**Comment by holyhope** [comment]
Okay for me to rename it to smth like `HarborHelmSpec`. For migration (upgrade) We will add extra properties in additional strcutures
