### ISSUE TITLE
Update Spilo from spilo-12:1.6-p3 -> spilo-14:2.1-p7

### ISSUE THREAD

**Issue by William-Young-97** [goharbor/harbor-operator#977]
#### Description

We have been using wal-g to for database recovery with the in cluster high availability version of Postgres. Due to Spilo being outdated wal-g and other components are also outdated. This has blocked us from being able to use the database recovery functionality when deploying with in cluster Postgres.

#### Fix

I will create a pull request with the relevant version update hardcoded in to `pkg > image > components.go`
 
#### Considerations 

For deeper context please refer to [here](https://github.com/giantswarm/harbor-operator-app/blob/backup-and-restore-readme/CLONE_RESTORE.md).

Pull request: #980

**Comment by thcdrt** [comment]
Fixed in #980
