### ISSUE TITLE
To implement auto assinee GH action

### ISSUE THREAD

**Issue by OrlinVasilev** [goharbor/harbor-operator#982]
Hi all,

I think we should  implement GH action - auto assign like we have for the main repository:
https://github.com/goharbor/harbor/blob/main/.github/auto-assignees.yml
https://github.com/goharbor/harbor/blob/main/.github/workflows/auto_assign_prs.yml

which will allow us to reduce the time to monitor the PRs coming in and to reduce the time to respond to new PRs
 
Please share your thoughts!

Orlix

**Comment by MarcelMue** [comment]
I took the liberty and implemented this issue here: https://github.com/goharbor/harbor-operator/pull/983

**Comment by MarcelMue** [comment]
This is done & can be closed.

**Comment by OrlinVasilev** [comment]
Thank you @MarcelMue !
