### ISSUE TITLE
Some configuration yaml files only exist in /charts and missing in the kustomization files at config/ 

### ISSUE THREAD

**Issue by steven-zou** [goharbor/harbor-operator#99]
- config/Manager

and no mutating-webhook but patch file defined 'webhookcainjection_patch.yaml'

**Comment by steven-zou** [comment]
It's by design?

**Comment by holyhope** [comment]
`webhookcainjection_patch.yaml` no more contains mutating webhook patch, only validating one.

I restored `config/manager`

#102
